version: '3.8'

services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s
    ports:
      - "${PORT}:${PORT}/udp"
      - "27015:27015/udp"
    environment:
      # Server settings
      PUID: ${PUID}
      PGID: ${PGID}
      PORT: ${PORT}
      PLAYERS: ${PLAYERS}
      SERVER_PASSWORD: ${SERVER_PASSWORD}
      MULTITHREADING: ${MULTITHREADING}
      RCON_ENABLED: ${RCON_ENABLED}
      RCON_PORT: ${RCON_PORT}
      TZ: ${TZ}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      COMMUNITY: ${COMMUNITY}
      SERVER_NAME: ${SERVER_NAME}
      SERVER_DESCRIPTION: ${SERVER_DESCRIPTION}
      ALLOW_CONNECT_PLATFORM: ${ALLOW_CONNECT_PLATFORM}
      BACKUP_CRON_EXPRESSION: ${BACKUP_CRON_EXPRESSION}
      BACKUP_ENABLED: ${BACKUP_ENABLED}
      DELETE_OLD_BACKUPS: ${DELETE_OLD_BACKUPS}
      OLD_BACKUP_DAYS: ${OLD_BACKUP_DAYS}
      AUTO_UPDATE_CRON_EXPRESSION: ${AUTO_UPDATE_CRON_EXPRESSION}
      AUTO_UPDATE_ENABLED: ${AUTO_UPDATE_ENABLED}
      AUTO_UPDATE_WARN_MINUTES: ${AUTO_UPDATE_WARN_MINUTES}
      AUTO_REBOOT_CRON_EXPRESSION: ${AUTO_REBOOT_CRON_EXPRESSION}
      AUTO_REBOOT_ENABLED: ${AUTO_REBOOT_ENABLED}
      AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE: ${AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      DISCORD_PRE_UPDATE_BOOT_MESSAGE: ${DISCORD_PRE_UPDATE_BOOT_MESSAGE}
      DISCORD_POST_UPDATE_BOOT_MESSAGE: ${DISCORD_POST_UPDATE_BOOT_MESSAGE}
      DISCORD_PRE_START_MESSAGE: ${DISCORD_PRE_START_MESSAGE}
      DISCORD_PRE_SHUTDOWN_MESSAGE: ${DISCORD_PRE_SHUTDOWN_MESSAGE}
      DISCORD_POST_SHUTDOWN_MESSAGE: ${DISCORD_POST_SHUTDOWN_MESSAGE}
      # Game settings
      DIFFICULTY: ${DIFFICULTY}
      DEATH_PENALTY: ${DEATH_PENALTY}
      ENABLE_PLAYER_TO_PLAYER_DAMAGE: ${ENABLE_PLAYER_TO_PLAYER_DAMAGE}
      ENABLE_FRIENDLY_FIRE: ${ENABLE_FRIENDLY_FIRE}
      ENABLE_INVADER_ENEMY: ${ENABLE_INVADER_ENEMY}
      DROP_ITEM_ALIVE_MAX_HOURS: ${DROP_ITEM_ALIVE_MAX_HOURS}
      IS_MULTIPLAY: ${IS_MULTIPLAY}
      IS_PVP: ${IS_PVP}
      CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: ${CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP}
      ENABLE_DEFENSE_OTHER_GUILD_PLAYER: ${ENABLE_DEFENSE_OTHER_GUILD_PLAYER}
    volumes:
      - ./palworld:/palworld/
